<html>
<head>
  <title>Report | Download | PDF</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style>
  body {
    font-family: 'kalpurush', sans-serif;
  }

  table {
      border-collapse: collapse;
      width: 100%;
  }
  table, td, th {
      border: 1px solid black;
  }
  th, td{
    padding: 4px;
    font-family: 'kalpurush', sans-serif;
    font-size: 13px;
  }
  @page {
    header: page-header;
    footer: page-footer;
    background-image: url({{ public_path('images/logo_background.png') }});
    background-size: cover;              
    background-repeat: no-repeat;
    background-position: center center;
  }
  .graybackground {
    background: rgba(192,192,192, 0.7);
  }
  </style>
</head>
<body>
  <h2 align="center">
    <img src="{{ public_path('images/logo.png') }}" style="height: 50px; width: auto;"><br/>
    <span style="font-family: Calibri;">Innova Attendance Management Solution</span>
  </h2>
  <p align="center" style="padding-top: -20px;">
    <span style="font-size: 20px;">
      {{ $institute->name }}<br/>
      মাসিক উপস্থিতি রিপোর্ট ({{ bangla(date('F, Y')) }})
    </span><br/>
  </p>
  
  <div class="" style="padding-top: 0px;">
    <table class="">
      <tr>
        <th class="graybackground" width="30%">শিক্ষক</th>
        <th class="graybackground" width="27%">প্রবেশ</th>
        <th class="graybackground" width="27%">প্রস্থান</th>
        <th class="graybackground">অবস্থানকাল</th>
      </tr>
      @php
        $datearray = [];
        $counter1 = 0;
        $counter2 = 0;
        foreach($attendances as $attendance) {
          $datearray[date('mdy', strtotime($attendance->timestampdata))]['date'] = $attendance->timestampdata;
          $datearray2 = [];
          
          foreach($teachers as $teacher) {
            if(($attendance->device_pin == $teacher->device_pin)) {
              $datearray2[$teacher->id][$counter1]['timestampdata'] = $attendance->timestampdata;
              $datearray2[$teacher->id][$counter1]['name'] = $teacher->name;
              $datearray2[$teacher->id][$counter1]['phone'] = $teacher->phone;
              $datearray[date('mdy', strtotime($attendance->timestampdata))]['data'][$counter1] = $datearray2;
            }

          }
          
          $counter2++;
          $counter1++;
        }
      @endphp
      @foreach($datearray as $datesingles)
        @php
          $datesingleforarray = date('mdy', strtotime($datesingles['date']));
        @endphp
        <tr>
          <td colspan="4" class="graybackground">{{ date('F d, Y', strtotime($datesingles['date'])) }}</td>
        </tr>
        @foreach($datesingles['data'] as $datesingle)
          
          <tr>
              <td>{{ print_r($datesingle) }}</td>
              {{-- <td>
                {{ reset($teacher)['name'] }}<br/><small>যোগাযোগঃ {{ reset($teacher)['phone'] }}</small>
              </td>
              <td align="center">{{ bangla(date('F d, Y h:i A', strtotime(reset($teacher)['timestampdata']))) }}</td>
              <td align="center">
                @if(reset($teacher) != end($teacher))
                  {{ bangla(date('F d, Y h:i A', strtotime(end($teacher)['timestampdata']))) }}
                @endif
              </td>
              <td align="center">
                @if(reset($teacher) != end($teacher))
                  <span class="badge badge-success">{{ bangla(Carbon::parse(end($teacher)['timestampdata'])->diffForHumans(Carbon::parse(reset($teacher)['timestampdata']))) }}</span>
                @endif
              </td> --}}
            </tr>
        <tr>
          {{-- <td>{{ print_r($datesingle) }}</td> --}}
          {{-- <td>
            {{ reset($datesingle)['name'] }}<br/><small>যোগাযোগঃ {{ reset($datesingle)['phone'] }}</small>
          </td>
          <td align="center">{{ bangla(date('F d, Y h:i A', strtotime(reset($datesingle)['timestampdata']))) }}</td>
          <td align="center">
            @if(reset($datesingle) != end($datesingle))
              {{ bangla(date('F d, Y h:i A', strtotime(end($datesingle)['timestampdata']))) }}
            @endif
          </td>
          <td align="center">
            @if(reset($datesingle) != end($datesingle))
              <span class="badge badge-success">{{ bangla(Carbon::parse(end($datesingle)['timestampdata'])->diffForHumans(Carbon::parse(reset($datesingle)['timestampdata']))) }}</span>
            @endif
          </td> --}}
        </tr>
        @endforeach
      @endforeach
    </table>
  </div>
 
  <htmlpagefooter name="page-footer">
    <small>ডাউনলোডের সময়কালঃ <span style="font-family: Calibri;">{{ date('F d, Y, h:i A') }}</span></small><br/>
    <small style="font-family: Calibri; color: #6D6E6A;">Generated by: https://innovaatt.com (+88 01515297658)</small>
  </htmlpagefooter>
</body>
</html>